[package]
name = "mime_guess_test"
version = "0.1.0"
edition = "2021"

[dependencies]
mime_guess = { version = "2.0.5", default-features = false }

[build-dependencies]
mime_guess = { version = "2.0.5", default-features = false, features = [
    "rev-mappings",
] }
